environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  nodejs_version: 7
os: Visual Studio 2017 # Windows Server 2016
install:
  - ps: Install-Product node $env:nodejs_version
  - java -version
  - mvn --version
  - node --version
  - npm --version
  - npm install
build_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
test_script:
  - mvn package
  - mvn checkstyle:check
  - npm test
  - npm run lint-js
  - npm run lint-md
  - npm run lint-less
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - C:\Users\appveyor\.m2\ -> pom.xml
